import { StyleSheet } from 'react-native';

import { Theme } from '@/constants/theme';

export const profileStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Theme.gray50 },
  scroll: { padding: 16, paddingBottom: 40 },
  h1: { fontSize: 24, fontWeight: '800', color: Theme.gray900, marginBottom: 8 },
  sub: { fontSize: 14, color: Theme.gray600, marginBottom: 16, lineHeight: 20 },
  card: {
    backgroundColor: Theme.white,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: Theme.gray200,
    marginBottom: 12,
  },
  cardTitle: { fontSize: 16, fontWeight: '800', color: Theme.gray900, marginBottom: 8 },
  label: { fontSize: 12, fontWeight: '800', color: Theme.gray500, marginBottom: 4 },
  input: {
    borderWidth: 1,
    borderColor: Theme.gray200,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    fontSize: 16,
    color: Theme.gray900,
  },
  primary: { backgroundColor: Theme.accentBlue, paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  primaryText: { color: Theme.white, fontWeight: '800' },
  outline: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: Theme.gray300,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  outlineText: { color: Theme.gray800, fontWeight: '700' },
  orderCard: {
    backgroundColor: Theme.white,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Theme.gray200,
  },
  orderRef: { fontWeight: '800', color: Theme.gray900 },
  orderStatus: { marginTop: 4, color: Theme.primary, fontWeight: '700' },
  orderAmt: { marginTop: 6, fontWeight: '800', color: Theme.secondaryDark },
  empty: { color: Theme.gray500, marginBottom: 12 },
  hint: { color: Theme.gray600, fontSize: 13, marginBottom: 4 },
  msg: { textAlign: 'center', marginTop: 40, color: Theme.gray600, paddingHorizontal: 24, fontSize: 16 },
  modalCard: { borderTopLeftRadius: 18, borderTopRightRadius: 18, backgroundColor: Theme.white, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: Theme.gray900, marginBottom: 8 },
  modalSub: { fontSize: 14, color: Theme.gray600, marginBottom: 12 },
  modalRow: { flexDirection: 'row', gap: 10, marginTop: 8 },
  modalBtn: { flex: 1, paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  modalGhost: { borderWidth: 1, borderColor: Theme.gray300, backgroundColor: Theme.white },
});
