// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=<your-firebase-project-id>
// Then replace this file with the generated output.
//
// Until you run flutterfire configure, this file is a placeholder that will
// cause a compile error intentionally so you don't ship without real config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}',
        );
    }
  }

  // ── Replace the values below with those from flutterfire configure ────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApns0m7fHF8p7-id7Lm3KC17-JKAJXJ-g',
    appId: '1:411205791152:android:1bd873f64fe88734deba75',
    messagingSenderId: '411205791152',
    projectId: 'newbalan',
    storageBucket: 'newbalan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosClientId: 'REPLACE_WITH_IOS_CLIENT_ID',
    iosBundleId: 'com.newbalan.medical.delivery',
  );
}
